version: 2.1
# Fan in/Fan out job execution
jobs:
  build:
    docker:
      - image: 'circleci/python:latest'
        auth:
          username:
          password:
    steps:
      - checkout
      - run: echo 'hello world from the build step'

  accept_test_1:
    docker:
      - image: 'circleci/python:latest'
        auth:
          username:
          password:
    steps:
      - checkout
      - run: echo 'hello world from the accept_test_1 step'

  accept_test_2:
    docker:
      - image: 'circleci/python:latest'
        auth:
          username:
          password:
    steps:
      - checkout
      - run: echo 'hello world from the accept_test_2 step'

  accept_test_3:
    docker:
      - image: 'circleci/python:latest'
        auth:
          username:
          password:
    steps:
      - checkout
      - run: echo 'hello world from the accept_test_3 step'    
  
  deploy:
    docker:
      - image: 'circleci/python:latest'
        auth:
          username:
          password:
    steps:
      - checkout
      - run: echo 'This step is run only when all 3 accept tests are successfully completed'

workflows:
  version: 2
  build-accept-deploy:
    jobs:
      - build
      - accept_test_1:
          requires:
            - build
      - accept_test_2:
          requires:
            - build
      - accept_test_3:
          requires:
            - build      
      - deploy:
          requires:
            - accept_test_1
            - accept_test_2
            - accept_test_3