version: 2.1
# sequential job execution
jobs:
  build:
    docker:
      - image: 'circleci/python:latest'
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo 'hello world from the build step'

  test_1:
    docker:
      - image: 'circleci/python:latest'
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo 'hello world from the test_1 step'

  test_2:
    docker:
      - image: 'circleci/python:latest'
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo 'hello world from the test_2 step'
  
  deploy:
    docker:
      - image: 'circleci/python:latest'
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo 'hello world from the deploy step'

workflows:
  version: 2
  build-test-approval-deploy:
    jobs:
      - build
      - test_1:
          requires:
            - build
      - test_2:
          requires:
            - test_1
      - hold:
          type: approval
          requires:
            - test_2      
      - deploy:
          requires:
            - hold

