version: 2.1
# sequential job execution
jobs:
  build:
    docker:
      - image: 'circleci/python:latest'
        auth:
          username:
          password:
    steps:
      - checkout
      - run: echo 'hello world from the build step'

  test1:
    docker:
      - image: 'circleci/python:latest'
        auth:
          username:
          password:
    steps:
      - checkout
      - run: echo 'hello world from the test1 step'

  test2:
    docker:
      - image: 'circleci/python:latest'
        auth:
          username:
          password:
    steps:
      - checkout
      - run: echo 'hello world from the test2 step'
  
  deploy:
    docker:
      - image: 'circleci/python:latest'
        auth:
          username:
          password:
    steps:
      - checkout
      - run: echo 'hello world from the deploy step'

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - test1
      - deploy:
          requires:
            - test2

